## Quiz #0102 

#### Use a lambda function and map() to answer the following questions.

1). Add 1 to each element of the list 'a' and create another list. <br>

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new_list=map(lambda x: x+1,a)
print("the new list is:",list(new_list))

the new list is: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


2). Multiply element-wise the lists 'a' and 'b'. Show the result as another list.

a = [2, 4, 6, 8, 10]

b = [10, 8, 6, 4, 2]

In [ ]:
a = [2, 4, 6, 8, 10]
b = [10, 8, 6, 4, 2]
c=[]
for x,y in zip(a,b):
    c.append(x*y)
print("the new list is:",c)


the new list is: [20, 32, 36, 32, 20]


#### Use a lambda function and filter() to answer the following questions.

3). Find the multiples of 5 in the range 1~100. Show the result as a list.

In [ ]:
a = [i for  i in range(1, 101)]
multiples = filter(lambda x: x%5==0 , a)
print("the multiples of 5 in that range are:\n",list(multiples))

the multiples of 5 in that range are:
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


4). In the following list, find the values larger than 160. Show the result as a list.

a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]

In [ ]:
a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]
new_list = filter(lambda x: x>160 , a)
print("values that are larger that 160 are:\n",list(new_list))

values that are larger that 160 are:
 [160.3, 171.6, 165.34, 167.2, 161.1, 164.9]


5). In the following list, find the values larger than 160 and smaller than 165. Show the result as a list.

a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]

In [ ]:
a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]
new_list = filter(lambda x: x>160 and x<165 , a)
print(" values larger than 160 and smaller than 165 are:\n",list(new_list))

 values larger than 160 and smaller than 165 are:
 [160.3, 161.1, 164.9]


6). In the following list of names, extract only those stargin with 'J'. Show the result as a list.

a = ['Sara', 'Jack', 'Rebecca', 'Jennifer', 'Paul', 'Andrew', 'John']

In [ ]:
a = ['Sara', 'Jack', 'Rebecca', 'Jennifer', 'Paul', 'Andrew', 'John']
starting_with_J=filter(lambda x: x[0]=="J",a)
print("names that starts with 'J' are:\n",list(starting_with_J))

names that starts with 'J' are:
 ['Jack', 'Jennifer', 'John']
